import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper, UploadProvider } from '@/components/providers';
import { Header } from '@/components/Header';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <UploadProvider>
            <Header />
            {children}
          </UploadProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
