import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { Sidebar } from '@/components/Sidebar/Sidebar';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <div className="flex">
            <Sidebar />
            <main className="pl-20 md:pl-64 transition-all duration-300">{children}</main>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
